export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_FAIL = 'GET_CURRENT_WEATHER_FAIL';

export const GET_HOURLY_WEATHER = 'GET_HOURLY_WEATHER';
export const GET_HOURLY_WEATHER_SUCCESS = 'GET_HOURLY_WEATHER_SUCCESS';
export const GET_HOURLY_WEATHER_FAIL = 'GET_HOURLY_WEATHER_FAIL';

export const GET_DAILY_WEATHER = 'GET_DAILY_WEATHER';
export const GET_DAILY_WEATHER_SUCCESS = 'GET_DAILY_WEATHER_SUCCESS';
export const GET_DAILY_WEATHER_FAIL = 'GET_DAILY_WEATHER_FAIL';

export const GET_NEWS = 'GET_NEWS';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_FAIL = 'GET_NEWS_FAIL';

export const SEARCH_ACTION = 'SEARCH_ACTION';

export const GET_AIR_QUALITY = 'GET_AIR_QUALITY';
export const GET_AIR_QUALITY_SUCCESS = 'GET_AIR_QUALITY_SUCCESS';
export const GET_AIR_QUALITY_FAIL = 'GET_AIR_QUALITY_FAIL';

